### ISSUE TITLE
Inconsistent regression on latency mitigation

### ISSUE THREAD

**Issue by Cloudpattern** [Soreepeong/XivAlexander#315]
Hello,
For a while now I've been unable to get the same kind of latency mitigation on newer versions as I do on 1.14.8.43.

Testing has been challenging: the issue is very inconsistent, then there's the queue times (can't exit the game, switch versions and easily log back in) and there is some usual variation (which is sometimes very significant) due to network conditions. But I've tried upgrading twice (maybe even 3 times) and and every time I felt a regression, so I ran out of ideas to try to figure out what is going on.

I have tried unload then load-once to swap versions with the game running (to try to make sure both versions are in the same environment and that the improvement isn't based on different network conditions, for example). I did this twice and the performance was immediately improved after the switch to the old version.
I would appreciate any advice on how to do this the best way to make sure there is a regression, as I do not know if this is a valid way to test.

The regressions were felt on v1.14.8.46 and v1.14.8.47. I'm not sure 100% sure I tested on v1.14.8.44 and v1.14.8.45.

Regressions on newer versions seem to be (based on more testing on v1.14.8.47):
- Clipping (sometimes) when weaving on Mode 1 (which is otherwise the most stable after the upgrade; on 1.14.8.43 I use mode 3)
- Instability for the GCD and weaves: it (sometimes) takes longer for a weave to go off (I play GNB and Continuation is always the worst offender)
- More instances where a skill apparently goes off but doesn't (or the other way around and then everything happens at the same time). Again, Continuation is the worst offender. I press Continuation but end up losing that oGCD because Continuation resets at the last moment before it's time for the GCD.

I read about about over-mitigation on older versions, so maybe I got used to a situation where there's too much latency mitigation? It doesn't quite feel like it because the mitigation just seems more stable...
Also, please let me know if testing 1.14.8.44 and v1.14.8.45 would be of any use and what kind of logs you need. However, because the issue is very inconsistent, I'm not sure how to proceed.
It kinda feels like the newer versions may be more sensitive to packet loss or varations, but for now I just want to make sure I'm testing it the right way.

My setup has about 185ms ping with a VPN. Tested all modes and Mode 3 seems to have the worst regression, and while Mode 2 has no clipping, it's still unstable due to other 2 issues mentioned above. Mode 3 is a coin toss.

**Comment by Soreepeong** [comment]
* Mode 1 is most dependent on the server load.
* Mode 3 also is dependent on the server load, if measuring ICMP ping is unavailable due to network restrictions.
* Version .44, .45 and .46 had a problem where measurement required for mode 3 being just wrong, which got fixed in .47, problem being mixed usage of milliseconds and microseconds unit.

Since Continuation gets activated by GCD actions, it will require the server to acknowledge and process your GCD, and then let your client know that Continuation can be used, and if that part is late, then your next GCD will be clipped. If either server or network isn't up to par for playing GNB, then for this case, XivAlexander can't really fix that.

But if this does not happen on .43, then do test out both .43 and .47, and post the log files saveable from the log window, both with Mode 2 and Mode 3. Make sure to have `Use Logging` ticked. To test out different version, use Uninstall XivAlexander to make it not load along with the game, and then use Load Once to switch versions without restarting the game.

**Comment by Cloudpattern** [comment]
I guess I must have definitely felt that issue on .44/.45/.46, which perhaps has maybe me a bit wary of upgrading. The latest version is definitely improved, but something still feels a bit "wrong."

I have collected some quick logs (will be able to do more later). However, I have found that the issue seems to happen more inside instances than when hitting striking dummies, and twice I tried the load/unload process while inside instances XivAlexander has crashed a little while after the second load, which may complicate testing a bit more than expected. Curiously, the game itself doesn't crash (I can still logout and even play, though Alexander says the game must exit).

It seems the "Prevent Early Firing" option helps with the instability I mentioned -- but again, it may be run-to-run variance, so I need to test more.

[logs.zip](https://github.com/Soreepeong/XivAlexander/files/7881704/log
[new version with prevent early firing enabled.zip](https://github.com/Soreepeong/XivAlexander/files/7881720/new.version.with.prevent.early.firing.enabled.zip)
s.zip)

**Comment by Cloudpattern** [comment]
I guess you're right. I guess unloading wasn't working correctly - that's probably what was causing the crash as well. I tried again and the old version still crashed after unloading (even after trying to unload twice, once from XivAlexander's own menu and another after starting xivAlexander and using Load Once > Unload)

Here are some new logs from the old version captured when loading after a fresh game start for reference. I'll say none of the logs from the new version have yet captured the worst situations I've encountered, so I'll keep trying when I can. 

I'll also test the new version as soon as I'm able.
[log-old-redone.txt](https://github.com/Soreepeong/XivAlexander/files/7883563/log-old-redone.txt)

**Comment by Cloudpattern** [comment]
As far as I can see, the issue persists. For this reason, I logged a whole fight with both .43 and .48.

I may have also managed to find a specific sequence where both versions "sometimes" behave very differently: Gnashing Fang (or Burst Strike) + Rough Divide or Blasting Zone + Continuation. At some point, .48 was mitigating so much (I guess?) that the RD/BZ were going off at basically the same time as Continuation. For example, I saw the beam from Blasting Zone actually come out of the back or top of my character as the animation was simply entirely cut off/merged with Continuation.

I arrived at this upon noticing that the delay between Continuation coming up as available and actually executing seemed be increasing. I then noticed using another oGCD before Continuation would make sure enough time had passed to allow Continuation to off -- until the skills were getting glued together.

The strange thing is that after I reloaded .48, it started to behave very similar to .43. I don't know if this makes any sense, but it's almost like .48 is "drifting" in its mitigation - the longer it's running, the more it differs from .43, whereas .43 remains the same. If this makes any sense, it would explain why the problem seemed to happen only inside instances -- basically, after much testing on striking dummies, I'd finally try to run an instance with it and then the problem would manifest.

For this test, the fight logged with .48 was the third or fourth instance I was running with it. All the previous ones seemed OK. My plan was to run all normal raids with .48 to test and it started feeling "off" at the end of the 2nd, which I re-run to log.

Does this help or make sense at all?

[wholefight-logs-43-48.zip](https://github.com/Soreepeong/XivAlexander/files/7885240/wholefight-logs-43-48.zip)

**Comment by justin767** [comment]
> As far as I can see, the issue persists. For this reason, I logged a whole fight with both .43 and .48.
> 
> I may have also managed to find a specific sequence where both versions "sometimes" behave very differently: Gnashing Fang (or Burst Strike) + Rough Divide or Blasting Zone + Continuation. At some point, .48 was mitigating so much (I guess?) that the RD/BZ were going off at basically the same time as Continuation. For example, I saw the beam from Blasting Zone actually come out of the back or top of my character as the animation was simply entirely cut off/merged with Continuation.
> 
> I arrived at this upon noticing that the delay between Continuation coming up as available and actually executing seemed be increasing. I then noticed using another oGCD before Continuation would make sure enough time had passed to allow Continuation to execute - until the skills were getting glued together.
> 
> The strange thing is that after I reloaded .48, it started to behave very similar to .43. I don't know if this makes any sense, but it's almost like .48 is "drifting" in its mitigation - the longer it's running, the more it differs from .43, whereas .43 remains the same. If this makes any sense, it would explain why the problem seemed to happen only inside instances -- basically, after much testing on striking dummies, I'd finally try to run an instance with it and then the problem would manifest.
> 
> For this test, the fight logged with .48 was the third or fourth instance I was running with it. All the previous ones seemed OK. My plan was to run all normal raids with .48 to test and it started feeling "off" at the end of the 2nd, which I re-run to log.
> 
> Does this help or make sense at all?
> 
> [wholefight-logs-43-48.zip](https://github.com/Soreepeong/XivAlexander/files/7885240/wholefight-logs-43-48.zip)

I have been experiencing the similar issue with MCH.

Versions .47 and .48 performs inconsistently in terms of their latency mitigation, whereas for version .43, the performance is rather stable.

The weird thing is, .47 and .48 seems to 'over-mitigate' latencies for the first few minutes, but the inconstancy kicks in after few minutes into the game, where in some extreme cases, my GCDs end up clipping.

I'm using Mode 3 btw.

**Comment by Cloudpattern** [comment]
I have switched to Mode 2 with Reduce Packet Delay to off and turned on the Fast Connect option in Mudfish (do you also use mudfish, perhaps?). Mode 3 doesn't work with Fast Connect, so it was off, but for Mode 2 I find it actually works better with Fast Connect on. That has been so far the best arrangement to be able to use the latest version. If you have a similar setup, maybe it's worth a try.

Mode 1 doesn't seem to mitigate enough no matter the version, but it's I think it's still an issue that Mode 3 has this regression. In previous versions it was the best, to the point I had disabled Fast Connect to be able to use it.
